# Generated by Django 3.2.10 on 2022-05-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_auto_20220423_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, default='./static/daa.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='daa.png', null=True, upload_to='profile/'),
        ),
    ]
