# Generated by Django 3.2.10 on 2022-05-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartment_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='order_type',
        ),
    ]
