# Generated by Django 3.2.10 on 2022-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('sender', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
