# Generated by Django 3.2.10 on 2022-08-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='RT4ERN2WM', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='8EM3MAFNM', max_length=255, unique=True),
        ),
    ]
