# Generated by Django 3.2.10 on 2022-07-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="short_id",
            field=models.CharField(default="R7ABX0DXI", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.CharField(default="ZL5SO0QFG", max_length=255, unique=True),
        ),
    ]
