# Generated by Django 3.2.10 on 2022-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220407_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='T460YA7SJ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='70HHIRVOC', max_length=255, unique=True),
        ),
    ]
