# Generated by Django 3.2.10 on 2022-08-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220819_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='L3J85UTGT', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='Q3VGDXE4L', max_length=255, unique=True),
        ),
    ]
