# Generated by Django 3.2.10 on 2022-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220224_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='QPRLPL8JT', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='U7WQ4CQ8R', max_length=255, unique=True),
        ),
    ]
