# Generated by Django 3.2.10 on 2022-06-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220607_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='YJI44M75K', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='QOAU1D61H', max_length=255, unique=True),
        ),
    ]
