# Generated by Django 3.2.10 on 2022-02-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220217_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='WLGYGUHQZ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='FMAG5RDEN', max_length=255, unique=True),
        ),
    ]
