# Generated by Django 3.2.10 on 2022-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20220523_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='ESZZDER25', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='6NEAAIK6N', max_length=255, unique=True),
        ),
    ]
