# Generated by Django 3.2.10 on 2022-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20220225_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='3I2IAGE4L', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='U6BXALXM9', max_length=255, unique=True),
        ),
    ]
