# Generated by Django 3.2.10 on 2022-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20220528_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='6YJ3M5SYH', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='WUDKELTNY', max_length=255, unique=True),
        ),
    ]
