# Generated by Django 3.2.10 on 2022-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20220531_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='HMD43CZEH', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='3ASJO1UCB', max_length=255, unique=True),
        ),
    ]
