# Generated by Django 3.2.10 on 2022-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20220906_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='3JP2UYUEL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='ASTEUA3CG', max_length=255, unique=True),
        ),
    ]
