# Generated by Django 3.2.10 on 2022-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20220419_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='3R0Y0R04F', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='DVYABGV7D', max_length=255, unique=True),
        ),
    ]
