# Generated by Django 3.2.10 on 2022-05-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_auto_20220502_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='0JY0EL0OA', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='OQJG9QX3H', max_length=255, unique=True),
        ),
    ]
