# Generated by Django 3.2.10 on 2022-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20220602_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='F9H6J6TFT', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='HN84GWHO2', max_length=255, unique=True),
        ),
    ]
