# Generated by Django 3.2.10 on 2022-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20220602_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='WLA8XGH7P', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='Z8TFWR55M', max_length=255, unique=True),
        ),
    ]
