# Generated by Django 3.2.10 on 2022-06-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0016_auto_20220603_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='MX18T6YJ8', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='K29DG7NL3', max_length=255, unique=True),
        ),
    ]
