# Generated by Django 3.2.10 on 2022-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_auto_20220629_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='GHJC6914Z', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='B9G04CR4Y', max_length=255, unique=True),
        ),
    ]
