# Generated by Django 3.2.10 on 2022-04-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_auto_20220406_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateroom',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PrivateRoom',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
