# Generated by Django 3.2.10 on 2022-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_auto_20220629_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='F8E18F670', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='ISPT3XAA6', max_length=255, unique=True),
        ),
    ]
