# Generated by Django 3.2.10 on 2022-06-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_auto_20220603_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='SWZ2I7CA0', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='I1JHJSM1X', max_length=255, unique=True),
        ),
    ]
