# Generated by Django 3.2.10 on 2022-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_auto_20220629_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='BZR1IW89L', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='LPU080OKI', max_length=255, unique=True),
        ),
    ]
