# Generated by Django 3.2.10 on 2022-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0020_auto_20220603_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='MA935I8KP', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='W06EPIC0Z', max_length=255, unique=True),
        ),
    ]
