# Generated by Django 3.2.10 on 2022-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_auto_20220603_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='N94NTFPMY', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='SQ0G9AAC1', max_length=255, unique=True),
        ),
    ]
