# Generated by Django 3.2.10 on 2022-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0023_auto_20220603_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='UXECR1LDF', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='DDT8NWF60', max_length=255, unique=True),
        ),
    ]
