# Generated by Django 3.2.10 on 2022-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0025_auto_20220603_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='1DJ6IL2FB', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='IAHQY6IJA', max_length=255, unique=True),
        ),
    ]
