# Generated by Django 3.2.10 on 2022-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0026_auto_20220603_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='GFVBF3SRX', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='WADYGJA7G', max_length=255, unique=True),
        ),
    ]
