# Generated by Django 3.2.10 on 2022-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0028_auto_20220603_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='2SPX9XT7L', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='YT9MFB7OD', max_length=255, unique=True),
        ),
    ]
