# Generated by Django 3.2.10 on 2022-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0029_auto_20220603_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='81V2QM6T5', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='WJYUFZWMT', max_length=255, unique=True),
        ),
    ]
