# Generated by Django 3.2.10 on 2022-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0031_auto_20220603_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='AN91F79ZN', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='FZWQA4559', max_length=255, unique=True),
        ),
    ]
