# Generated by Django 3.2.10 on 2022-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0033_auto_20220603_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='8YOKRK2W3', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='LQ0VP8VUJ', max_length=255, unique=True),
        ),
    ]
