# Generated by Django 3.2.10 on 2022-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0035_auto_20220603_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='7Y895KF9Y', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='IXDFFWJ6N', max_length=255, unique=True),
        ),
    ]
