# Generated by Django 3.2.10 on 2022-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0037_auto_20220603_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='O61OKGF82', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='45Q7FMSA7', max_length=255, unique=True),
        ),
    ]
