# Generated by Django 3.2.10 on 2022-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0038_auto_20220603_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='6GB55E55P', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='RBUE90LA9', max_length=255, unique=True),
        ),
    ]
