# Generated by Django 3.2.10 on 2022-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0043_auto_20220603_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='3JHIPX0GY', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='K4LZZN79S', max_length=255, unique=True),
        ),
    ]
