# Generated by Django 3.2.10 on 2022-06-07 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('aparment_title', models.CharField(max_length=40, verbose_name='Apartment Title')),
                ('category', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('Flats', 'Flats'), ('Self Contain', 'Self Contain')], max_length=20)),
                ('videofile', models.FileField(null=True, upload_to='video/')),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('agent', models.CharField(max_length=30, null=True)),
                ('descriptions', models.CharField(max_length=250)),
                ('feautures', models.CharField(max_length=250)),
                ('location_info', models.CharField(max_length=250)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('apartment', models.ManyToManyField(to='apartment.Apartment')),
            ],
        ),
    ]
