# Generated by Django 3.2.10 on 2022-06-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='aparment_title',
            new_name='apartment_title',
        ),
    ]
