# Generated by Django 3.2.10 on 2022-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='reviews',
            field=models.JSONField(null=True),
        ),
    ]
