# Generated by Django 3.2.10 on 2022-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='order_type',
            field=models.CharField(choices=[('All', 'All'), ('Active', 'Active'), ('Closed', 'Closed')], default='All', max_length=10, null=True),
        ),
    ]
