# Generated by Django 3.2.10 on 2022-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_apartment_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image_url',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
