# Generated by Django 3.2.10 on 2022-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_apartment_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image_url',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
