# Generated by Django 3.2.10 on 2022-02-15 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=40)),
                ('agent_account_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('account_number', models.CharField(max_length=20)),
                ('account_bank', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('debit_currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3)),
                ('account_id', models.CharField(max_length=60)),
                ('withdrawal_date', models.DateTimeField()),
            ],
        ),
    ]
