# Generated by Django 3.2.10 on 2022-02-10 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('account_number', models.CharField(max_length=20)),
                ('account_bank', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('debit_currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3)),
                ('account_id', models.CharField(max_length=30)),
                ('withdrawal_date', models.DateTimeField()),
            ],
        ),
    ]
