# Generated by Django 3.2.10 on 2022-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_payment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.UUIDField()),
                ('sender', models.CharField(max_length=30, null=True)),
                ('recipient', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('date_sent', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.CharField(max_length=40)),
                ('agent_account_number', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('history_time', models.DateTimeField(auto_now_add=True)),
                ('account_bank', models.CharField(max_length=4, null=True)),
                ('narration', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('debit_currency', models.CharField(max_length=3, null=True)),
                ('account_id', models.CharField(blank=True, max_length=60, null=True)),
                ('transaction_status', models.CharField(max_length=12, null=True)),
                ('withdrawal_date', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
