# Generated by Django 3.2.10 on 2022-08-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_auto_20220714_2219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenthistory",
            name="room",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="short_id",
        ),
        migrations.DeleteModel(
            name="Rooms",
        ),
    ]
