# Generated by Django 3.2.10 on 2022-02-15 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220215_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
