# Generated by Django 3.2.10 on 2022-02-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20220215_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-history_time']},
        ),
    ]
