# Generated by Django 3.2.10 on 2022-04-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20220404_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='K3TIQDLJW', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='LJBA311Z5', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
