# Generated by Django 3.2.10 on 2022-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_auto_20220602_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='X2W48CQR9', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='GJ99CD84Y', max_length=255, unique=True),
        ),
    ]
