# Generated by Django 3.2.10 on 2022-06-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0021_auto_20220629_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='G64RX2KQ4', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='04NBVVBKS', max_length=255, unique=True),
        ),
    ]
