# Generated by Django 3.2.10 on 2022-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_auto_20220629_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='2TIOAVSUU', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='CQB1RBMNR', max_length=255, unique=True),
        ),
    ]
