# Generated by Django 3.2.10 on 2022-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0028_auto_20220603_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='PXRQ2GSR9', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='U002WP869', max_length=255, unique=True),
        ),
    ]
