# Generated by Django 3.2.10 on 2022-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0031_auto_20220603_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='short_id',
            field=models.CharField(default='P28E4KADD', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='HDYJDKE4P', max_length=255, unique=True),
        ),
    ]
