# Generated by Django 3.2.10 on 2022-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='user',
            name='agent_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
