# Generated by Django 3.2.10 on 2022-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name=' Verification Code ')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=' Generation time ')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
