# Generated by Django 3.2.10 on 2022-04-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20220419_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home_address',
        ),
    ]
