# Generated by Django 3.2.10 on 2022-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20220419_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, default='https://nigerianbuildingdesigns.com/wp-content/uploads/2021/01/3-2-1.jpg', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://nigerianbuildingdesigns.com/wp-content/uploads/2021/01/3-2-1.jpg', null=True, upload_to='profile/'),
        ),
    ]
