# Generated by Django 3.2.10 on 2022-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20220419_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, default='/static/daa.png', null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='daa.png', null=True, upload_to='profile/'),
        ),
    ]
