# Generated by Django 3.2.10 on 2022-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20220419_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, default='./static/daa.png', null=True, upload_to='profile/'),
        ),
    ]
